{"kind":"symbol","sections":[],"metadata":{"externalID":"s:10Foundation14LocalizedErrorPAAE16errorDescriptionSSSgvp::SYNTHESIZED::s:7SwiftPy11PythonErrorO","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"8.0","name":"iOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"10.10","name":"macOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"9.0","name":"tvOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"2.0","name":"watchOS"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"relatedModules":["Foundation"],"name":"SwiftPy"}],"title":"errorDescription","extendedModule":"Foundation"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/errorDescription"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/SwiftPy\/documentation\/SwiftPy","doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"LocalizedError.errorDescription"},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/swiftpy\/pythonerror\/errordescription"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://SwiftPy/documentation/SwiftPy":{"role":"collection","url":"\/documentation\/swiftpy","abstract":[{"text":"A fast and lightweight Python interpreter with Swift macro binding tools.","type":"text"}],"type":"topic","title":"SwiftPy","identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy","kind":"symbol"},"doc://SwiftPy/documentation/SwiftPy/PythonError/errorDescription":{"identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/errorDescription","title":"errorDescription","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/swiftpy\/pythonerror\/errordescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic"},"doc://SwiftPy/documentation/SwiftPy/PythonError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PythonError","kind":"identifier"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"PythonError","kind":"identifier"}],"type":"topic","url":"\/documentation\/swiftpy\/pythonerror","identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError","role":"symbol","title":"PythonError"}}}