{"hierarchy":{"paths":[["doc:\/\/SwiftPy\/documentation\/SwiftPy","doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError"]]},"variants":[{"paths":["\/documentation\/swiftpy\/pythonerror\/error-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/localizedDescription"],"anchor":"Instance-Properties"}],"sections":[],"metadata":{"modules":[{"name":"SwiftPy"}],"role":"collectionGroup","title":"Error Implementations","roleHeading":"API Collection"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/Error-Implementations"},"references":{"doc://SwiftPy/documentation/SwiftPy/PythonError":{"abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"text":"PythonError","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PythonError","kind":"identifier"}],"title":"PythonError","url":"\/documentation\/swiftpy\/pythonerror","identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError"},"doc://SwiftPy/documentation/SwiftPy":{"identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy","title":"SwiftPy","role":"collection","url":"\/documentation\/swiftpy","abstract":[],"kind":"symbol","type":"topic"},"doc://SwiftPy/documentation/SwiftPy/PythonError/localizedDescription":{"role":"symbol","title":"localizedDescription","url":"\/documentation\/swiftpy\/pythonerror\/localizeddescription","type":"topic","identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/localizedDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","abstract":[]}}}