{"identifier":{"url":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"metadata":{"roleHeading":"API Collection","modules":[{"name":"SwiftPy"}],"role":"collectionGroup","title":"LocalizedError Implementations"},"variants":[{"paths":["\/documentation\/swiftpy\/pythonerror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","sections":[],"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/errorDescription","doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/failureReason","doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/helpAnchor","doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/recoverySuggestion"],"anchor":"Instance-Properties"}],"hierarchy":{"paths":[["doc:\/\/SwiftPy\/documentation\/SwiftPy","doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://SwiftPy/documentation/SwiftPy/PythonError/helpAnchor":{"title":"helpAnchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/swiftpy\/pythonerror\/helpanchor","type":"topic","identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/helpAnchor","abstract":[],"role":"symbol"},"doc://SwiftPy/documentation/SwiftPy/PythonError/recoverySuggestion":{"url":"\/documentation\/swiftpy\/pythonerror\/recoverysuggestion","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/recoverySuggestion","kind":"symbol","type":"topic","title":"recoverySuggestion","abstract":[]},"doc://SwiftPy/documentation/SwiftPy":{"identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy","title":"SwiftPy","role":"collection","url":"\/documentation\/swiftpy","abstract":[],"kind":"symbol","type":"topic"},"doc://SwiftPy/documentation/SwiftPy/PythonError":{"abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"text":"PythonError","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PythonError","kind":"identifier"}],"title":"PythonError","url":"\/documentation\/swiftpy\/pythonerror","identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError"},"doc://SwiftPy/documentation/SwiftPy/PythonError/failureReason":{"kind":"symbol","identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/failureReason","type":"topic","title":"failureReason","url":"\/documentation\/swiftpy\/pythonerror\/failurereason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"abstract":[],"role":"symbol"},"doc://SwiftPy/documentation/SwiftPy/PythonError/errorDescription":{"title":"errorDescription","identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/errorDescription","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[],"url":"\/documentation\/swiftpy\/pythonerror\/errordescription"}}}